version: "3.9"  # optional since v1.27.0
services:
  ag:
    container_name: firma_ag   
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 4000:4000

